# Generated by Django 3.1.1 on 2020-09-29 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='FirstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='LastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Date',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Title',
            new_name='title',
        ),
    ]
